name: Changelog

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: "!contains(github.event.head_commit.message, '[no changelog entry]')"
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1.0.3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Create local changes
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec github_changelog_generator -u andrewmcodes -p rubocop-linter-action --token ${{ secrets.GITHUB_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "andrewmcodes@protonmail.com"
        git config --local user.name "Andrew Mason"
        git commit -m "Update changelog" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
